CREATE TABLE IF NOT EXISTS `#__document_communication` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`ordering` INT(11)  NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`checked_out` INT(11)  NOT NULL ,
`checked_out_time` DATETIME NOT NULL ,
`created_by` INT(11)  NOT NULL ,
`modified_by` INT(11)  NOT NULL ,
`user_id` VARCHAR(255)  NOT NULL ,
`quote` VARCHAR(255)  NOT NULL ,
`title1` VARCHAR(255)  NOT NULL ,
`document1` TEXT NOT NULL ,
`title2` VARCHAR(255)  NOT NULL ,
`document2` TEXT NOT NULL ,
`title3` VARCHAR(255)  NOT NULL ,
`document3` TEXT NOT NULL ,
`title4` VARCHAR(255)  NOT NULL ,
`document4` TEXT NOT NULL ,
`title5` VARCHAR(255)  NOT NULL ,
`document5` TEXT NOT NULL ,
`title6` VARCHAR(255)  NOT NULL ,
`document6` TEXT NOT NULL ,
`title7` VARCHAR(255)  NOT NULL ,
`document7` TEXT NOT NULL ,
`title8` VARCHAR(255)  NOT NULL ,
`document8` TEXT NOT NULL ,
`title9` VARCHAR(255)  NOT NULL ,
`document9` TEXT NOT NULL ,
`title10` VARCHAR(255)  NOT NULL ,
`document10` TEXT NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8mb4_unicode_ci;

