CREATE TABLE IF NOT EXISTS `#__payment_message` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`ordering` INT(11)  NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`checked_out` INT(11)  NOT NULL ,
`checked_out_time` DATETIME NOT NULL ,
`created_by` INT(11)  NOT NULL ,
`modified_by` INT(11)  NOT NULL ,
`flightyesnormalpayment` TEXT NOT NULL ,
`quotation_requestfyn` TEXT NOT NULL ,
`finalquotation_fyn` TEXT NOT NULL ,
`firstinstalment_fyn` TEXT NOT NULL ,
`finalinstalment_fyn` TEXT NOT NULL ,
`tripfyn` TEXT NOT NULL ,
`flight_no_normalpayment` TEXT NOT NULL ,
`quotation_requestfnn` TEXT NOT NULL ,
`finalquotation_fnn` TEXT NOT NULL ,
`firstinstalment_fnn` TEXT NOT NULL ,
`finalinstalment_fnn` TEXT NOT NULL ,
`trip_fnn` TEXT NOT NULL ,
`flight_yes_split_payment` TEXT NOT NULL ,
`quotation_requestfys` TEXT NOT NULL ,
`finalquotation_fys` TEXT NOT NULL ,
`firstinstalment_fys` TEXT NOT NULL ,
`finalinstalment_fys` TEXT NOT NULL ,
`tripfys` TEXT NOT NULL ,
`flight_no_splitpayment` TEXT NOT NULL ,
`quotation_requestfns` TEXT NOT NULL ,
`finalquotation_fns` TEXT NOT NULL ,
`flightyespartipayment` TEXT NOT NULL ,
`flight_no_parti_payment` TEXT NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8mb4_unicode_ci;

