CREATE TABLE IF NOT EXISTS `#__create_trip` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`ordering` INT(11)  NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`checked_out` INT(11)  NOT NULL ,
`checked_out_time` DATETIME NOT NULL ,
`created_by` INT(11)  NOT NULL ,
`modified_by` INT(11)  NOT NULL ,
`title` VARCHAR(255)  NOT NULL ,
`description` TEXT NOT NULL ,
`type` VARCHAR(255)  NOT NULL ,
`date_of_departure1` DATE NOT NULL ,
`price_person1` INT NOT NULL ,
`price_single_room_extra1` INT NOT NULL ,
`cost_hotel1` INT NOT NULL ,
`cost_activites1` INT NOT NULL ,
`cost_transport1` INT NOT NULL ,
`pdfplanning1` TEXT NOT NULL ,
`seat_available1` INT NOT NULL ,
`keeper1` VARCHAR(255)  NOT NULL ,
`transport1` VARCHAR(255)  NOT NULL ,
`hotel1` VARCHAR(255)  NOT NULL ,
`inclusion1` TEXT NOT NULL ,
`noinclusion1` TEXT NOT NULL ,
`planning1` VARCHAR(255)  NOT NULL ,
`number_of_day1` VARCHAR(255)  NOT NULL ,
`pdfplanning2` TEXT NOT NULL ,
`pdfplanning3` TEXT NOT NULL ,
`pdfplanning4` TEXT NOT NULL ,
`pdfplanning5` TEXT NOT NULL ,
`pdfplanning6` TEXT NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8mb4_unicode_ci;

